# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'TestApplication' do
  use_frameworks!
  
  pod "Torus-utils",  :path => '../'
  # Pods for TestApplication
  
  target 'TestApplicationTests' do
    # Pods for testing
  end
  
  post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
    end
  end

end
