# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'
target 'TestApplication' do
  use_frameworks!
  
#  pod 'Torus-fetchNodeDetails', :git=>'https://github.com/torusresearch/fetch-node-details-swift'
  pod "Torus-utils",  :path => '../'
  # Pods for TestApplication
  
  target 'TestApplicationTests' do
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end

end
